### ISSUE TITLE
Symlinks for files not correctly created

### ISSUE THREAD

**Issue by tlartaud** [timkelty/shipit-shared#18]
Hi,

I come back to you because i found a syntax error which cause symlinks for files not always working.
See incoming PR for more informations.

**Comment by tlartaud** [comment]
The old syntax leave an error 

```
bash-4.3$ $(readlink -n "/staging.domain.com/releases/20150509081352/.env")
bash: /var/www/vhosts/domain.com/staging.domain.com/shared/.env: No such file or directory
```

The new one is ok 

```
bash-4.3$ readlink /staging.domain.com/releases/20150509081352/.env
/var/www/vhosts/domain.com/staging.domain.com/shared/.env
```

**Comment by tlartaud** [comment]
@timkelty do you agree with that fix ?

**Comment by timkelty** [comment]
I think so, yep. I'll review and merge it in later today.

**Comment by timkelty** [comment]
shipit-shared@3.1.1
