### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by timkelty** [timkelty/shipit-shared#2]

**Comment by alpacaaa** [comment]
I was randomly googling for a way to have shared files in shipit, looks like you got it! Even a simple README would be awesome to start using this. Thanks :+1:

**Comment by timkelty** [comment]
I know, I'm sorry about that!

I'll work on it for this (and all my other shipit tasks) this weekend!
Thanks for calling me out, needed it.

**Comment by alpacaaa** [comment]
Hey don't worry! And thank you for looking into it! :)

**Comment by timkelty** [comment]
All set, @alpacaaa

**Comment by alpacaaa** [comment]
Looks great man, thanks ;)

**Comment by timkelty** [comment]
I'll add some tests when I get time too.
