### ISSUE TITLE
Cannot read property 'triggerEvent' of undefined

### ISSUE THREAD

**Issue by tim-field** [timkelty/shipit-shared#28]
Started getting this error with no stack trace during command line usage. Maybe related to npm / node upgrades?

Cannot read property 'triggerEvent' of undefined

Just using like so in shipitfile.js file
require('shipit-shared')(shipit);

**Comment by tim-field** [comment]
Duh, seems this project didn't need shipit-shared, and not having any shared config seems to cause this

**Comment by timkelty** [comment]
ah hah! well it probably shouldn't throw an error.
I'll reopen to fix
