### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by garygreen** [timkelty/shipit-shared#34]
The docs are a little confusing about the `path` property when you already define the path above it. Why do you need both `config/environment.yml` and `path: 'config/database.yml'` ? I'm really confused by that structure (especially how the path is outside the object)

``` javascript
  shipit.initConfig({
    default: {
      shared: {
        overwrite: true,
        dirs: [
          'public/storage',
          {
            path: 'db',
            overwrite: false,
            chmod: '-R 777',
          }
        ],
        files: [
          'config/environment.yml',
          {
            path: 'config/database.yml',
            overwrite: false,
            chmod: '755',
          }
        ],
      }
    }
  });
```

**Comment by timkelty** [comment]
I agree the docs need some clarificaiton.

When you symlink `files`, you need to specify each one. In this case I need both files `config/environment.yml` and `config/database.yml` to be symlinked.

As for `config/environment.yml` being a string and the other being an object, that's just an example of how they can be either. If you want use all default options, you can just specify paths as strings. If you want to set options specific to that path, you can use an object. Note that `files` and `dirs` are arrays, so each item in the array can be either a string (path) OR an object.

**Comment by garygreen** [comment]
Oh ok thanks. I totally missed that they were separate `dirs` and `files` -- does symlink really care? Not sure there needs to be a distinction? Everything in linux is a file.

I think docs do need a bit more clarification as it had me a bit confused. It may be an idea to promote either an array of objects OR an array of strings but not a mixture (even though it's supported). It's a bit confusing and looks weird :eyes:

**Comment by timkelty** [comment]
`files` and `dirs` being separate initially comes from the fact that `shipit-shared` started as a port of the 'linked_files`/`linked_dirs` functionality from [Capistrano](http://capistranorb.com/documentation/getting-started/structure/)

If they're not separate, it becomes a headache to determine when and where we need to create the necessary parent directories.

**Comment by timkelty** [comment]
Docs in general need help :grimacing: 

I'll close this in lieu of https://github.com/timkelty/shipit-shared/issues/35
I'll try and get to it soon, otherwise open to PRs.
