### ISSUE TITLE
Cannot create symlink, because shipit-shared created directory

### ISSUE THREAD

**Issue by PhilippBaschke** [timkelty/shipit-shared#38]
I am not sure if I miss something or understand something wrong; **Sorry if I do**!

I have the following scenario:

``` JavaScript
config = {
  // Do not create the folder because it should be a symlink
  ignores: ["app/uploads"],
  shared: {
    // no overwrite: true because the directory app/uploads should not exist in releases folder
    dirs: ["app/uploads"]
}
```

I expect **shipit-shared** to create `shared/app/uploads` and a symlink `releases/xxx/app/uploads -> shared/app/uploads` but it fails with the following error: 

```
Error: Cannot create shared symlink, file exists at "/releases/xxx/app/uploads".
See https://github.com/timkelty/shipit-shared/#sharedoverwrite for more information.
```

As far as I understand the offending `/releases/xxx/app/uploads` directory is created by [create-dirs.js:46](https://github.com/timkelty/shipit-shared/blob/master/tasks/shared/create-dirs.js#L46). 
If I run **shipit** without **shipit-shared** `/releases/xxx/app/uploads` does not exist.

**Comment by timkelty** [comment]
Your description makes sense, sounds like your understanding is correct.
**Note:** You shouldn't need the `ignores` line explicitly, assuming `app/uploads` is .gitignored.

Can you try setting `shared.overwrite = true` in your config?

It defaults to false for reasons detailed [here](https://github.com/timkelty/shipit-shared/#sharedoverwrite), but probably will change [soon](https://github.com/timkelty/shipit-shared/issues/30).

**Comment by PhilippBaschke** [comment]
Thank you for the Note. That is good to know ;)

`shared.overwrite = true` works. It seemed strange to me that the directory is created just to be deleted (I guess I do not understand the reason why it is created properly).
I just wanted to make you (and other users) aware that this error might occur.

**Comment by timkelty** [comment]
It is strange (and quite silly). It will definitely be changing with the next version.

Quick history/explanation:

> It seemed strange to me that the directory is created just to be deleted

It actually is just creating all the parent directories _up until_ the symlink. This is so the symlink command doesn't fail. This isn't actually this problem.

Initially, `shipit-shared` worked exactly how you would have expected, no `overwrite` required. Just before it makes the symlink, it would `rm -rf` the _target_ of the symlink. This is so it would overwrite any existing symlink, or anything else that might erroneously prevent the symlink from being created.

Certain users were using `shipit-shared` a bit differently and _really_ didn't like the fact that it `rm -rf`d that spot in current (even though if you're using it as expected, it shouldn't matter). Therefore, we ended up with the `overwrite` setting. https://github.com/timkelty/shipit-shared/issues/17

At the very least, it should default to true. Sorry for the confusion, I'll post something here once it is changed. Thanks!

**Comment by PhilippBaschke** [comment]
Thank you for taking the time to clarify. 
I'll just set `overwrite: true`.
Thank you for the module by the way. Helps a lot. :+1:

**Comment by timkelty** [comment]
No problem, thanks for using it.
