### ISSUE TITLE
Shipit-shared incompatible with latest shipit-deploy ?

### ISSUE THREAD

**Issue by tlartaud** [timkelty/shipit-shared#43]
Hi there, Hi @timkelty  !

Dunno if you are still working on this, but I recently updated shipit-deploy to latest version, and this is not working. I got some blank resultst in the console.
```
[06:24 ]-[vagrant@vm]-[/var/www]-[git develop]
$ grunt shipit:production shared
Running "shipit:production" (shipit) task

Running "shared:create-dirs" task
Running "if [ -h /var/www/vhosts/domain.com/httpdocs/current ]; then readlink /var/www/vhosts/domain.com/httpdocs/current; fi" on host "server.com".
@server.com releases/20161121165404
Creating shared directories on remote.

Running "shared:set-permissions" task
Setting permissions on remote.
Permissions set on remote.

Running "shared:link:dirs" task

Running "shared:link:files" task

Running "shared:end" task

Done.


Execution Time (2016-11-21 18:30:07 UTC+1)
loading tasks           891ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 53%
shared:create-dirs      703ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 42%
shared:set-permissions   40ms  ▇ 2%
Total 1.7s
```

To make it work again, I had to rollback to old version by specifying them in my package.json
```
    "shipit-deploy": "2.2.0",
    "shipit-shared": "4.4.1",
    "shipit-cli": "1.4.1",
    "shipit-utils": "1.3.1"
```

Would you plan to check it out ?

The problem is that shared option are not passed to shipit-shared. I always get the defaults when I try to console.log shipit options at differents places in your node
```

{ symlinkPath: '/var/www/vhosts/domain.com/httpdocs/shared',
  files: [],
  dirs: [],
  basePath: '/var/www/vhosts/domain.com/httpdocs/shared',
  overwrite: false,
  remote: true,
  chmod: false,
  isFile: false,
  shipitMethod: 'remote' }
```

Regards.

**Comment by timkelty** [comment]
I'll check it out today.

**Comment by timkelty** [comment]
Can you reinstall and make sure you have `shipit-cli@1.5.2` and try again?

There was a change to how defaults are merged in that was published as a non-breaking change, but should have been published as a breaking change.

Details here: https://github.com/shipitjs/shipit/issues/137

**Comment by tlartaud** [comment]
hi, thank you for this answer ! do you mean I need to add something else than grunt-shipit and shipit-shared on m'y package.json ? Actualités, I was just adding them. grunt-shipit was installing shipit-cli and shipit-utils himself so I wasnt registering it. Maybe it wasnt installing the last versions ? I'll check it out and Will let u know

**Comment by timkelty** [comment]
`grunt-shipit` requires `shipit-cli@^1.0.1`, which as of now should install `1.5.2`.

At some point, it may have installed `shipit-cli@1.5.1`, which had a breaking change that should not have been published, and was fixed in `1.5.2`.

I would just delete your `node_modules` and reinstall.

**Comment by tlartaud** [comment]
This is what I have actually in my Project stack generator :

`package.json`
```
"dependencies": {
    "builtin-modules": "^1.1.0",
    "chance": "^1.0.3",
    "dotenv": "^2.0.0",
    "glob": "^7.0.5",
    "grunt": "^1.0.1",
    "grunt-bump": "^0.8.0",
    "grunt-checkbranch": "^1.0.2",
    "grunt-checkpending": "^1.0.1",
    "grunt-contrib-clean": "^1.0.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-less": "^1.3.0",
    "grunt-contrib-uglify": "^1.0.1",
    "grunt-conventional-changelog": "^6.1.0",
    "grunt-curl": "^2.2.0",
    "grunt-exec": "^1.0.0",
    "grunt-git": "^1.0.0",
    "grunt-lineending": "^1.0.0",
    "grunt-prompt": "^1.3.0",
    "grunt-shell": "^1.1.2",
    "grunt-shipit": "^1.0.0",
    "grunt-text-replace": "^0.4.0",
    "grunt-then": "^1.0.0",
    "grunt-zip": "^0.17.1",
    "load-grunt-config": "^0.19.2",
    "load-grunt-tasks": "^3.2.0",
    "remote-origin-url": "^0.5.1",
    "semver": "^5.0.3",
    "shipit-deploy": "^2.0.0",
    "shipit-shared": "^4.4.0",
    "spdx-correct": "^1.0.1",
    "spdx-expression-parse": "^1.0.0",
    "time-grunt": "^1.2.1"
  }
```

```
$ npm ls grunt-shipit
+-- UNMET PEER DEPENDENCY grunt@1.0.1
`-- grunt-shipit@1.0.0

npm ERR! peer dep missing: grunt@^0.4.4, required by grunt-shipit@1.0.0
```

```
$ npm ls shipit-deploy
`-- shipit-deploy@2.4.0
```

```
$ npm ls shipit-cli
`-- grunt-shipit@1.0.0
  `-- shipit-cli@1.5.1
```

```
$ npm ls shipit-utils
`-- shipit-deploy@2.4.0
  `-- shipit-utils@1.4.0
```

```
$ npm ls shipit-shared
`-- shipit-shared@4.4.2
```

So, apparently, wrong versions are getting installed. Not sure why .. It looks like shipit-cli is installed as a child of grunt-shipit, like if it was bundle inside it. Maybe that just adding explicitly shipit-cli version 1.5.2 in my package.json file fix the problem.

**Comment by timkelty** [comment]
Hmm not sure either. Maybe something is cached.

`shipit-cli@1.5.1` is your problem. Make sure you have `shipit-cli@1.5.2`.
Which, if you re-install everything, should happen, since `grunt-shipit` requires `shipit-cli@^1.0.1`

**Comment by tlartaud** [comment]
This is a fresh install, I ran npm install for the first time on a new project created to test this

**Comment by timkelty** [comment]
Not sure what to tell you then...1.5.2 is the latest published version of `shipit-cli` in that revision range:

```
❯ npm view shipit-cli versions

[ '0.0.0',
  '0.0.1',
  '1.0.0',
  '1.0.1',
  '1.1.0',
  '1.2.0',
  '1.2.1',
  '1.3.0',
  '1.4.0',
  '1.4.1',
  '1.5.1',
  '1.5.2',
  '2.0.0' ]
```

**Comment by tlartaud** [comment]
Ok, don't know why it was not installing the latest version, anyway, thanks for pointing me out the correct version.

I've just added `"shipit-cli": "^1.5.2"` to my package.json and ran npm install and it installed the correct version. Will try a deploy soon, but I'm pretty sure it will work now, be cause I had testing and isolated the problem, and it was, as you said, a merge problem with the `_.defaults()` fonction from lodash that was not doing the expected job.

Thanks a lot.

**Comment by timkelty** [comment]
Sounds good!

**Comment by tlartaud** [comment]
I will publish this stack in a few weeks. If you are interested to see how I use your plugin, do not hesitate to follow https://github.com/wp-jungle ;)
