### ISSUE TITLE
config.dirs and config.files shouldn't be required

### ISSUE THREAD

**Issue by alpacaaa** [timkelty/shipit-shared#5]
Finally got a chance to try this, I noticed that it breaks if you don't specify either `dirs` or `files`. Gonna send a pull request soon!

**Comment by timkelty** [comment]
Thanks! Yet another reason I need to add some tests.

I basically did what you did, but also added an init method for setting any kinds of defaults.

**Comment by alpacaaa** [comment]
Awesome thanks!
